config/routes.rb
Rails.application.routes.draw do
  devise_for :people
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#home"

  get 'zarinpal' => 'home#pay'
  get 'aboneh' => 'home#pay'
  match '/pay' => 'zarinpal#pay', via: :post
  match '/pay' => 'zarinpal#pay', via: :get
  get 'zarinpal/:id' => 'zarinpal#verify'
  get '/profile' => 'home#profile'
  get '/:id' => 'home#redirect'
  post '/recover_password' => 'home#recover_password'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="">
<head>
  <title>Abonmaan</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <noscript><link rel="stylesheet" href="assets/noscript.css" /></noscript>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>
<body>
  <div style="top:5px;" class="error">
    <p style="color:white;">
      <% if alert=="Invalid Mobile number or password." %>
      شماره موبایل یا رمز عبور اشتباه است.
      <% else %>
      <%= alert %>
      <% end %>
    </p>
  </div>
  <!-- Wrapper-->
  <div id="wrapper">

    <nav id="nav">
      <a href="#me" class="icon fa-home active"> خانه </a>
      <a href="#profile" class="icon fa-user"> حساب من </a>
      <a href="#aboneh" class="icon fa-credit-card" style="color:#5175f3"> پرداخت </a>
      <a href="#telegram" class="icon fa-send"> پشتیبانی </a>
      <br>
    </nav>

    <!-- Main -->
    <div id="main">
      <!-- Me -->
      <article id="me" class="panel">
        <header>
          <h1>
            همیار
            خطابه غدیر و فدک
          </h1>
          <p style="text-align: justify; direction: rtl;line-height: 25px;">
            به منظور راه اندازی
            سیستمی جهت مکانیزه کردن آبونه مجموعه و برداشتن قدمی در خدمت به ساحت مقدس حضرت ولی عصر علیه السلام
            سیستم همیار آبونمان خطابه غدیر و فدک راه اندازی شده است.
            در صورتیکه علاقه مند هستید مشترک آبونمان شوید لطفا با شماره تلفن
            ۰۹۱۰۲۲۷۵۸۸۱
            تماس بگیرید تا اقدامات لازم جهت ثبت نام شما صورت گیرد.
            <br>
            <span style="color:green;">
              شماره کارت جهت واریز آبونمان‌ (<%= BankAccount.last.name %>):
            </span>
            <br>
            <strong style="font-size: 35px;color:green;"><%= BankAccount.last.card_number %></strong>
            <br>
            <br>
            <span id="mid_div">
              <a href="#telegram" class="button" style="margin-bottom: 2%;"> پشتیبانی </a>
              <a href="#aboneh" class="button" style="    background-color: #4f71e8;
              color: #eaebed;margin-bottom: 2%;"> پرداخت </a>
              <a href="#profile" style="margin-bottom: 2%;" class="button"> حساب من </a>
            </span>
            </p>

        </header>
        <div class="row">
          <div class="3u 12u$(mobile)" style="float:right!important">
            <a href="#profile" class="jumplink pic">
              <span class="arrow icon fa-chevron-right"><span>پروفایل</span></span>
              <!-- <img src="images/me.jpg" alt="" /> -->
              <%= image_tag "me.jpg" %>
            </a>
          </div>
          <div class="9u 12u$(mobile)" style="float:left!important">

          </div>
        </div>

      </article>

      <!-- Work -->
      <article id="profile" class="panel" style="direction: rtl; ">
        <% if not person_signed_in? %>
        <header>
          <h2>
            ورود
          </h2>
        </header>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <!-- <form action="#" method="post"> -->
        <div>
          <div class="row">
            <div class="6u 12u$(mobile)" style="float:right!important">
              <!-- <input type="number" name="name" placeholder="شماره موبایل"  /> -->
              <%= f.number_field :mobile_number, autofocus: true, placeholder: "شماره موبایل" %>
            </div>
            <div class="6u 12u$(mobile)">
              <%= f.password_field :password, autocomplete: "off" , placeholder: "رمز عبور" %>
              <!-- <input type="password" name="email" placeholder="رمز عبور" /> -->
            </div>
            <div class="12u$">
              <input type="submit" value="ثبت" style="float:left"/>
              <input type="button" id="recover_password" value="بازیابی رمز عبور" style="float:right"/>
            </div>
          </div>
        </div>
        <% end %>

        <div class="row">
          <div class="12u$">
          </div>
        </div>

        <% else %>
        <header>
          <h2>
            پرداخت های من
          </h2>
        </header>
        <div class="row" style="direction rtl;">
          <div class="4u 12u$(mobile)">
            پرداخت بعدی :
            <small>
              <% date = current_person.payments.wating.last.deadline %>
              <%= date.to_pdate.strftime("%e %b %Y") %>
            </small>
          </div>
          <div class="4u 12u$(mobile)">
            پرداخت شده ها  : <%= current_person.payments.done.sum(:amount).to_i%> تومان
          </div>
          <div class="4u 12u$(mobile) ">
            دوره ها :<%= current_person.payments.count%>
          </div>
        </div>
        <section>
          <div class="row" style="direction:rtl;">
            <% current_person.payments.order("deadline desc").each do |p| %>
            <div class="4u 12u$(mobile)" style="float: right;">
              <div class="payment" style=" background-image: url(images/pic0<%=rand(1..9)%>.jpg); background-size:cover;">
                <p style="margin-top:1%">
                  تاریخ:
                  <%= p.deadline.to_pdate.strftime("%e %b %Y")%>
                  <br>
                  مبلغ:
                  <%= p.amount.to_i %> تومان
                  <br>
                  شناسه پیگری :
                  <%= p.uid %>
                </p>
                <p style="border-top: solid 1px;">
                  <%= p.farsi_status %>
                </p>
              </div>
            </div>
            <% end %>
          </div>
        </section>
        <div class="12u$">
          <%= link_to('خروج', destroy_person_session_path, :method => :delete , class: "button pull-left" , style: " text-decoration: none;") %>
        </div>
        <% end %>

        <br>
      </article>

      <!-- Contact -->
      <article id="aboneh" class="panel">
        <header style="direction: rtl;">
          <h2 style="text-align:center;">
            پرداخت آبونه
          </h2>
        </header>
        <% if person_signed_in? or (@person.present? and not @person.new_record?)  %>
        <form action="/pay" method="POST">
          <div>
            <div class="row">
              <div class="12u$ "style="direction:rtl;">
                <!-- input value is persons ignored payments plus wating payments -->
                <input type="text" style="text-align:center" readonly name="amount" placeholder=" مبلغ را وارد کنید:" value="<%= @person.amount_for_the_person.to_i if @person.present? %>" />
              </div>
              <div class="12u$">
                <input type="hidden" name="person_id" value="<%= @person.id%>" >
                <p style="direction: rtl; text-align:center;">
                  <%= @person.name %> - آبونه بعدی : <%= @person.payments.wating.last.deadline.to_pdate.strftime("%b")%>  ماه
                  <% if @person.payments.ignored.any? %>
                  <br>
                  به همراه
                  آبونه
                  <% @person.payments.ignored.each do |i| %>
                  <%= i.deadline.to_pdate.strftime("%b %y") %> |
                  <% end %>
                </p>
                <% end %>
                <input type="submit" value="پرداخت کُن" />
              </div>
            </div>
          </div>
        </form>
        <% else %>
        <div class="row" >
          <div class="12u$ "style="direction:rtl;">
            <p>
              در صورتیکه مشترک آبونمان خطابه غدیر و فدک هستید، بوسیله لینک مخصوصی که برای شما ارسال شده است، و یا با
              ورود از قسمت
              <i class="icon fa-user"> </i>
              می توانید نسبت به پرداخت آبونه خود اقدام نمایید.
            </p>
            <p>
              در صورت تمایل به عضویت در این طرح با شماره پشتیبانی
              ۰۹۱۰۲۲۷۵۸۸۱
              تماس حاصل نمایید تا اقدامات لازم برای عضویت شما صورت گیرد.
            </p>
          </div>
        </div>
        <% end %>

      </article>

      <!-- <article id="info" class="panel">
      <header style="direction: rtl;">
      <h2 style="text-align:center;">
      آبونه چیست؟
    </h2>
  </header>
</article> -->

<article id="telegram" class="panel">
  <header style="direction: rtl;">
    <h2 style="text-align:center;">
      پشتیبانی سامانه آبونمان خطابه غدیر و فدک
    </h2>
    <p style="text-align:justify;">
      برای ارتباط با ما می توانید
      از شماره زیر استفاده نمایید و یا به آی دی تلگرام ما پیام ارسال کنید.
      ما در زودترین زمان با شما تماس خواهیم گرفت.
    </p>
    <p style="text-align:center;">
      شماره تماس:
      <span style="">
        <a href="tel:+989102275881"> ۰۹۱۰۲۲۷۵۸۸۱ </a>
      </span>
    </p>

    <p style="text-align:center;">
      تلگرام:
      <span style="">
        <%= link_to "abonman_khetabe@" , "https://telegram.me/abonman_khetabe" %>
      </span>
    </p>

  </header>
</article>
</div>

<%#= yield %>

<!-- Footer -->
<div id="footer">
  <ul class="copyright">
    <li>&copy; KhetabeGhadir.com</li>
    <li>
      طراحی توسط گروه انفورماتیک<a href="http://khetabeghadir.com" style="text-decoration:none;">
        خطابه غدیر و فدک</a>
      </li>
      <li>
        <%= link_to "مدیر" , "/admin" , style: "text-decoration:none;"%>
      </li>
    </ul>
  </div>
</div>

<div id="modal1" style="display: none; direction: rtl; position: fixed; z-index: 8; left: 50%; top: 50px; margin-left: -300px; margin-top: 0px;">
  <div class="row" >
    <div class="12u$(mobile) "style="direction:rtl;">
      <p style="color:white;">
        جهت بازیابی رمز عبور، لطفا شماره موبایل خود را وارد کنید:
      </p>
      <%= form_tag recover_password_path do %>
      <%= number_field_tag :mobile_number, nil ,autofocus: true, :required => true, style: "text-align:center;" , placeholder: "شماره موبایل" %>
      <br>
      <%= show_simple_captcha %>
      <input type="submit" value="ثبت" style="background-color:#7373d9; float:left;"/>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>

<script type="text/javascript">

  $('#modal1').easyModal({
  	top: '50%',
  	overlayOpacity: 0.9,
  });

  $('#recover_password').click(function(e){
  	$('#modal1').trigger('openModal');
  	e.preventDefault();
  });

</script>